#!/usr/bin/env python3
"""Regenerate `kolibri-core/src/logo.rs` from `assets/kolibri.svg`.

Packs 1 bpp, MSB-first rows as `ImageRaw` expects; a set bit is a lit pixel.
Besides the master pose (wing up) it renders two more wing poses for the
flight animation, by swapping the master's wing for the paths in WING_POSES.
Requires Inkscape and Pillow. Run from the repository root:

    python3 tools/gen-logo.py
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image

SVG = Path("assets/kolibri.svg")
OUT = Path("kolibri-core/src/logo.rs")

# (rust_const, width, height, ink_threshold, where it is used, also facing right)
# A higher threshold fattens the bird; the 40x30 one needs it to keep its beak.
# Widths are multiples of 8 so rows pack into whole bytes.
SIZES = [
    ("LARGE", 64, 48, 128, "the boot splash", False),
    ("SMALL", 40, 30, 165, "the status screen", True),
]

SUPERSAMPLE = 8

# The wing as it appears in the master path, and the smooth back that replaces
# it when the wing is drawn as a separate shape.
MASTER_WING = "C 75,32 98,19 118,9\n        C 104,28 86,45 69,56"
BARE_BACK = "C 62,43 67,49 69,56"

# (const suffix, wing path) for the animation poses, in viewBox coordinates.
WING_POSES = [
    # The master wing rotated 50 degrees down about the shoulder, at 80%.
    ("MID", "M 63,41 C 78,48 98,55 115,62 C 96,63 76,61 61,56 Z"),
    # Hand-drawn: a broad blade below the belly, clear of the tail.
    ("DOWN", "M 52,50 C 46,66 48,82 56,92 C 64,84 72,70 74,56 Z"),
]


def posed(master: str, wing: str) -> str:
    """The master SVG with its wing replaced by `wing`."""
    if MASTER_WING not in master:
        sys.exit(f"{SVG}: wing segment not found; update MASTER_WING")
    body = master.replace(MASTER_WING, BARE_BACK)
    return body.replace("<circle", f'<path fill="#12A594" d="{wing}"/>\n  <circle', 1)


def rasterise(svg: str, width: int, height: int, threshold: int) -> Image.Image:
    """Render SVG source to 1 bit, anti-aliasing before thresholding."""
    with tempfile.TemporaryDirectory() as tmp:
        src, png = Path(tmp) / "in.svg", Path(tmp) / "out.png"
        src.write_text(svg)
        subprocess.run(
            [
                "inkscape", str(src),
                "--export-type=png",
                f"--export-filename={png}",
                "-w", str(width * SUPERSAMPLE),
                "-h", str(height * SUPERSAMPLE),
                "-b", "#ffffff",
            ],
            check=True,
            capture_output=True,
        )
        grey = Image.open(png).convert("L").resize((width, height), Image.LANCZOS)
    return grey.point(lambda p: 255 if p < threshold else 0, mode="1")


def pack(bitmap: Image.Image) -> list[int]:
    """Pack a 1-bit image into MSB-first rows padded to whole bytes."""
    width, height = bitmap.size
    px = bitmap.load()
    data = []
    for y in range(height):
        for byte_x in range(0, width, 8):
            byte = 0
            for bit in range(8):
                x = byte_x + bit
                if x < width and px[x, y]:
                    byte |= 0x80 >> bit
            data.append(byte)
    return data


def render_rust() -> str:
    out = [
        "//! The kolibri hummingbird, packed for the OLED.",
        "//!",
        "//! Generated by `tools/gen-logo.py` from `assets/kolibri.svg` -- edit the",
        "//! vector master and rerun the script rather than touching the bytes here.",
        "",
        "use embedded_graphics::{image::ImageRaw, pixelcolor::BinaryColor};",
        "",
    ]

    master = SVG.read_text()
    for name, width, height, threshold, used_by, mirror in SIZES:
        frames = [(name, master, f"hummingbird for {used_by}")]
        frames += [
            (f"{name}_{pose}", posed(master, wing), f"{pose.lower()} wing pose")
            for pose, wing in WING_POSES
        ]
        images = [rasterise(svg, width, height, threshold) for _, svg, _ in frames]
        for (const, _, what), image in zip(frames, images):
            out += bitmap(const, image, what)
        out += wing_set(f"{name}_WINGS", [c for c, _, _ in frames], width, height, "")

        if mirror:
            for (const, _, what), image in zip(frames, images):
                flipped = image.transpose(Image.FLIP_LEFT_RIGHT)
                out += bitmap(f"{const}_RIGHT", flipped, f"{what}, facing right")
            consts = [f"{c}_RIGHT" for c, _, _ in frames]
            out += wing_set(f"{name}_WINGS_RIGHT", consts, width, height, ", facing right")

    return "\n".join(out)


def wing_set(name: str, consts: list[str], width: int, height: int, facing: str) -> list[str]:
    return [
        f"/// The {width}x{height} wing poses{facing}, up to down, for the flight animation.",
        f"pub const {name}: [ImageRaw<'static, BinaryColor>; {len(consts)}] ="
        f" [{', '.join(consts)}];",
        "",
    ]


def bitmap(name: str, image: Image.Image, what: str) -> list[str]:
    width, height = image.size
    data = pack(image)
    rows = width // 8
    out = [
        f"/// {width}x{height} {what}, one row of pixels per line.",
        "#[rustfmt::skip]",
        f"const {name}_DATA: [u8; {len(data)}] = [",
    ]
    for y in range(height):
        out.append("    " + " ".join(f"0x{b:02x}," for b in data[y * rows:(y + 1) * rows]))
    return out + [
        "];",
        "",
        f"/// The {width}x{height} {what}, ready to hand to `Image::new`.",
        f"pub const {name}: ImageRaw<'static, BinaryColor> ="
        f" ImageRaw::new(&{name}_DATA, {width});",
        "",
    ]


def main() -> int:
    if not SVG.exists():
        print(f"{SVG} not found -- run from the repository root", file=sys.stderr)
        return 1
    OUT.write_text(render_rust())
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
