#!/usr/bin/env python3
"""Regenerate `kolibri-core/src/logo.rs` from `assets/kolibri.svg`.

Packs 1 bpp, MSB-first rows as `ImageRaw` expects; a set bit is a lit pixel.
Requires Inkscape and Pillow. Run from the repository root:

    python3 tools/gen-logo.py
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image

SVG = Path("assets/kolibri.svg")
OUT = Path("kolibri-core/src/logo.rs")

# (rust_const, width, height, ink_threshold, where it is used)
# A higher threshold fattens the bird; the 40x30 one needs it to keep its beak.
# Widths are multiples of 8 so rows pack into whole bytes.
SIZES = [
    ("LARGE", 64, 48, 128, "the boot splash"),
    ("SMALL", 40, 30, 165, "the status screen"),
]

SUPERSAMPLE = 8


def rasterise(width: int, height: int, threshold: int) -> Image.Image:
    """Render the SVG and reduce it to 1 bit, anti-aliasing before thresholding."""
    with tempfile.NamedTemporaryFile(suffix=".png") as tmp:
        subprocess.run(
            [
                "inkscape", str(SVG),
                "--export-type=png",
                f"--export-filename={tmp.name}",
                "-w", str(width * SUPERSAMPLE),
                "-h", str(height * SUPERSAMPLE),
                "-b", "#ffffff",
            ],
            check=True,
            capture_output=True,
        )
        grey = Image.open(tmp.name).convert("L").resize((width, height), Image.LANCZOS)
    return grey.point(lambda p: 255 if p < threshold else 0, mode="1")


def pack(bitmap: Image.Image) -> list[int]:
    """Pack a 1-bit image into MSB-first rows padded to whole bytes."""
    width, height = bitmap.size
    px = bitmap.load()
    data = []
    for y in range(height):
        for byte_x in range(0, width, 8):
            byte = 0
            for bit in range(8):
                x = byte_x + bit
                if x < width and px[x, y]:
                    byte |= 0x80 >> bit
            data.append(byte)
    return data


def render_rust() -> str:
    out = [
        "//! The kolibri hummingbird, packed for the OLED.",
        "//!",
        "//! Generated by `tools/gen-logo.py` from `assets/kolibri.svg` -- edit the",
        "//! vector master and rerun the script rather than touching the bytes here.",
        "",
        "use embedded_graphics::{image::ImageRaw, pixelcolor::BinaryColor};",
        "",
    ]

    for name, width, height, threshold, used_by in SIZES:
        data = pack(rasterise(width, height, threshold))
        rows = width // 8
        out += [
            f"/// {width}x{height} hummingbird for {used_by}, one row of pixels per line.",
            "#[rustfmt::skip]",
            f"const {name}_DATA: [u8; {len(data)}] = [",
        ]
        for y in range(height):
            row = data[y * rows:(y + 1) * rows]
            out.append("    " + " ".join(f"0x{b:02x}," for b in row))
        out += [
            "];",
            "",
            f"/// The {width}x{height} hummingbird, ready to hand to `Image::new`.",
            f"pub const {name}: ImageRaw<'static, BinaryColor> ="
            f" ImageRaw::new(&{name}_DATA, {width});",
            "",
        ]

    return "\n".join(out)


def main() -> int:
    if not SVG.exists():
        print(f"{SVG} not found -- run from the repository root", file=sys.stderr)
        return 1
    OUT.write_text(render_rust())
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
